#+title: Reference



This ship which sails between the stars...

"The great decks are flat, so that a sailor on one part can signal to his mate some distace away; if they are curved, with surfaces everywhere equidistant from the hunger of the ship, separated hands would be concealed from each other, as ships were hidden from one another under the horizons of Urth. But because they are flat, they seem always to slant, unless one stands at the center. Thus I felt, light though I was, that I climbed a ghostly hill."

"Because I felt my whole being but a tissue of feathers, I had supposed I would rise slowly, floating upward as I had been told sailors floated in the rigging. It was not so. I leaped as swiftly and perhaps more swiftly than anyone here on Ushas, but I did not slow, as such a leaper begins to slow almost at once. The first speed of my leap endured unabated - up and up I shot, and the feeling was wonderful and terrifying."

"Absurd though it seemed, I somehow felt that my weight, which had been only slight on the tier of my cabin diminished further as I descended. Earlier, when I had climbed the rigging, I had noticed that it dwindled as I ascended; it therefore followed that it should increase as I moved down from level to level in the bowels of the ship. I can only say that it was not so, or at least that it did not seem so to me, but the very reverse of that."



